Estado del arte
antoniogamiz/tfg pull request #10
Opened 2021-11-08 20:22 UTC by antoniogamiz

2022-03-04 19:02 UTC, JJ commented
Todo lo que hagas tiene que estar en un milestone, incluyendo PRs.

2022-03-14 17:44 UTC, JJ commented
Tienes que *enlazar* la historia de usuario y los issues con los problemas que vayas resolviendo. *Todos* los aspectos del proyecto tienen que resolver un problema para alguien, así que *siempre* tiene que haber un estado del arte. ¿Por qué se hace el estado del arte? ¿Qué se puede concluir de él? ¿Qué *es* un estado del arte?
 Y todavía no has entregado el milestone 1. Si no tienes la configuración, flujos de trabajo de test y demás, no puedes empezar con el siguiente.

2022-03-14 18:04 UTC, antoniogamiz commented
Cuando te refieres a enlazar la historia de usuario, ¿a qué te refieres? Estoy haciendo una historia de usuario por milestone y el milestone ya está enlanzado al issue.

2022-03-14 18:06 UTC, JJ commented
@antoniogamiz A que crees explícitamente un issue con cada historia de usuario. Una historia de usuario no puede ser nunca un milestone, porque en cada milestone se va a crear un producto relativo o que afecte a varias historias de usuario. Milestone == PMV. Historia de usuario: beneficio que un usuario pretende obtener con esta aplicación.

2022-04-20 17:39 UTC, JJ requested changes
Obstáculo principal es el tema de la intro al capítulo y demás. Tampoco sé cuál es el scope de este PR. ¿Es sólo iniciarlo, o escribirlo completo?

2022-04-20 17:39 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +Los word embeddinng son una técnica de la rama del procesamiento del lenguaje natural que ayuda a capturar la semántica y el contexto sintáctico para comprender cómo de parecidos o diferentes son los
En el hito 0 tendrías que tener el workflow de CI para comprobar la ortografía. Lo digo porque ahí hay un par de faltas.
En todo caso tienes que ser más explícito en todos los capítulos, diciendo de qué va el capítulo, por qué es importante, de esta forma
"En el capítulo anterior, hablamos de no sé qué. Como dijimos, hacía falta x. Aquí explicamos x"
Por otro lado, igual tendrías que hablar de embedding en general, para luego particularizar a word embedding, y luego explicar qué lo que queremos hacer es un embedding, pero para otras cosas.

2022-04-20 17:39 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +En el modelo \emph{word2vec} \cite{word2vec:1} \cite{word2vec:2}, se crea una representación en forma vector para cada palabra. Los vectores son elegidos de forma que una simple función matemática, c
Similitud "semántica", eso es lo importante.
También lo principal es que se puede hacer aritmética con las palabras, y se pueden crear representaciones únicas de conjuntos de palabras (frases).

2022-04-20 17:39 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +En el caso de este trabajo, los tropos no tienen, a priori, distintos sentidos, por lo que se ha optado por usar el modelo \emph{word2vec}.
Bueno, pueden tenerlos, porque se puede subvertir el tropo. No en una primera aproximación, claro.

2022-04-23 11:36 UTC, antoniogamiz commented on doc/secciones/03_estado_del_arte.tex
> +Los word embeddinng son una técnica de la rama del procesamiento del lenguaje natural que ayuda a capturar la semántica y el contexto sintáctico para comprender cómo de parecidos o diferentes son los
Ciertamente, done.

2022-04-23 11:36 UTC, antoniogamiz commented on doc/secciones/03_estado_del_arte.tex
> +En el modelo \emph{word2vec} \cite{word2vec:1} \cite{word2vec:2}, se crea una representación en forma vector para cada palabra. Los vectores son elegidos de forma que una simple función matemática, c
Aclarado.

2022-04-23 11:37 UTC, antoniogamiz commented
Cierto, he corregido el scope, esto es una versión inicial. También he movido el PR al milestone 0, que estaba en el 1 por equivocación. También he actualizado con main y añadido el spell checker para corregir las faltas.

2022-04-23 17:20 UTC, JJ requested changes
Me temo que todavía necesita un pequeño repaso. También sería conveniente que definiéramos un poco más el scope del PR. hay definir clarametne qué imperfección se va a admitir... Si se va a limitar a la materia que se ha incluido ahora mismo, aún así debería ser más preciso.

2022-04-23 17:20 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +continuación los \textit{word embeddings}, que son una parte fundamental del trabajo. Por
¿Por qué son una parte fundamental del trabajo?

2022-04-23 17:20 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +hacer de forma que las películas que sean similares entre sí, tengan representaciones similares (cercanas).
Similares, ¿en qué sentido? ¿Cuál es el criterio de similitud?

Tienes que abrir una HU que corresponda a satisfacer al tribunal, en el que va a haber tanto informáticos como matemáticos. Las descripciones conceptuales que hagas tienen que satisfacer a los dos.

2022-04-23 17:20 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +Cuando estos embeddings se usan para capturar el significado semántico de palabras, se suelen denominar
No has dicho hasta el momento nada de la semántica. El que de ese embedding emerja semántica no es trivial, y sobre todo en el estado del arte deberías de ser lo suficientemente preciso para mostrar al tribunal que entiendes por qué sucede (y pretendes aprovecharte de ello)

2022-04-23 17:20 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +Firth de que `una palabra se caracteriza por la compañía que mantiene' \cite{firth1957synopsis}. Por lo tanto,
Qué bueno. Pero igual tendrías que poner esto antes.

2022-04-23 17:20 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +En este trabajo, lo que se pretende es crear \textit{word embeddings} para tropos, con el fin de poder estudiar
No serían "word" sino "any" embeddings.

2022-04-23 17:20 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +\emph{fruta}, o la famosa operación \emph{rey} - \emph{hombre} + \emph{mujer} = \emph{reina}.
Si es famosa, pon una cita.

2022-04-23 17:20 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +el mismo word embedding es usado para kiwi y mango.
¿Y? ¿Esto tiene algo que ver con tu proyecto? ¿Los tropos tienen varios significados? ¿Piensas usarlos?
Recuerda el tropo de la pistola de Chejov o el del sable del samurai. Si mencionas algo, tienes que usarlo.

2022-04-23 17:20 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +\emph{kiwi y mango son frutas}.
¿Cómo se hace eso? ¿Un conjunto de entrenamiento para cada aparición?
En todo caso, ver arriba.

2022-04-23 17:20 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +En el caso de este trabajo, los tropos no tienen, a priori, distintos sentidos, por lo que se ha optado
Pues no lo menciones.

2022-04-23 17:20 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +por usar el modelo \emph{word2vec}.
Define "el modelo" word2vec. Si se trata de que hay un embedding por entidad, pues defínelo así.

2022-09-05 17:28 UTC, JJ commented
Uf, todavía esta este PR...

2022-09-13 15:38 UTC, JJ commented
Y tienes que resolver los conflictos...

2022-09-15 18:26 UTC, JJ commented
... y arreglar el error...

2022-09-15 18:32 UTC, JJ requested changes
Aparte de lo ya dicho, creo que lo que estás escribiendo tendría que ir en otra sección. Una sección del estado del arte tendría que hablar de cosas en dos direcciones: una, cómo se trabaja con tropos y para qué pueden servir, dos, cómo se atacan embeddings de cualquier tipo y qué implicaciones tiene.

2022-09-15 18:32 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +Este capítulo comienza con una descripción de los \textit{embeddings} para introducir a
La terminología deberías haberla definido en introducción, o en un capítulo específico de definiciones (incluyendo matemáticas)

2022-09-15 18:32 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +Un \textit{embedding} es un espacio dimensional con una dimensión relativamente pequeña, en la que se pueden
... aquí no deben ir las definiciones, esto es el estado del arte. También debes usar un entorno especial para las definiciones matemáticas. ¿Qué es un "espacio dimencional"?

2022-09-15 18:32 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +Cuando estos embeddings se usan para capturar el significado semántico de palabras, se suelen denominar
Antes tendrías que aclarar por qué los embedding tienen algo que ver con la semántica.
En todo caso, el estado del arte no es donde tienes que definir nada.

2022-09-15 18:32 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +A partir de una palabra se puede generar un vector que represente el valor semántico de tal palabra, es decir, qué signigica la palabra, qué caracteriza
Estás confundiendo embeddings específicos (de palabras) con el concepto general. Tampoco corresponde al estado del arte.

2022-09-15 18:32 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +De igual forma que se puede hacer con palabras, en este trabajo, lo que se pretende es crear \textit{any embeddings} para tropos, con el fin de poder estudiar
Pero para eso tendrías que hacer una pequeña explicación de por qué una proyección en un espacio de dimensiones fijas (más que menores dimensiones, aunque también es importante) genera algún tipo de semántica.

2022-09-18 16:45 UTC, JJ requested changes
Me tengo que ir, pero ve dándole una vuelta.

2022-09-18 16:45 UTC, JJ commented on doc/bibliografia.bib
> +  title={Overview of PicTropes, a film trope dataset},
Protege las mayúsculas en la bibliografía.

2022-09-18 16:45 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +En el análisis de datos de texto se suele encontrar el problema de la alta dimensionalidad de los datos. Por eso surgió el
Las definiciones tienen que ser matemáticas, con sus entornos correspondientes en LaTeX. Tienes también que incluir demostraciones de todas las afirmaciones que hagas, o referirte a las mismas si son triviales o excesivamente complicadas.

2022-09-18 16:45 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +Análisis Semántico Latente (o más conocido por LSA, \textit{Latent Semantic Analysis}), que es una técnica popular
cita

2022-09-18 16:45 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +\begin{definition}[Embedding]
¿No hay palabra en español? Usa cursivas si no.

2022-09-18 16:45 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +    Dado un conjunto de datos $D$, de tamaño $m\in\mathbb{N}$, un término $w\in D$, el embedding de $w$ es
Tienes que ser más preciso en las definiciones y que se adapten a todos los posibles usos de la misma.
Esta definición tampoco parece correcta; o tendrás que decir qué es un término antes de hablar de conjunto de datos.
Tal como lo estás contando, me da la impresión de que hablas simplemente de reducción de dimensionalidad, y no es así. Lo que hace el embedding es convertir dimensiones en un espacio de muchísimas dimensiones (palabras dentro de un conjunto) en vectores en un espacio de dimensión fija, en función de la correlación que hay entre esas dimensiones (cómo las palabras aparecen juntas)

2022-09-18 16:45 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +La motivación para usar \textit{embeddings} con palabras proviene de la idea de John Rupert
correlación entre dimensiones. No hables del contexto que *no* vas a usar, sino del que vas a usar. Cuando puedas, mete ejemplos propios.

2022-09-19 10:20 UTC, antoniogamiz commented on doc/secciones/03_estado_del_arte.tex
> +continuación los \textit{word embeddings}, que son una parte fundamental del trabajo. Por
Porque es en lo que se va a general principalmente. Quiero decir, el trabajo va a generar embeddings de tropos. Voy a cambiarlo a que forman parte de la base entonces.

2022-09-19 10:20 UTC, antoniogamiz commented on doc/secciones/03_estado_del_arte.tex
> +Firth de que `una palabra se caracteriza por la compañía que mantiene' \cite{firth1957synopsis}. Por lo tanto,
Hecho.

2022-09-19 10:20 UTC, antoniogamiz commented on doc/secciones/03_estado_del_arte.tex
> +Cuando estos embeddings se usan para capturar el significado semántico de palabras, se suelen denominar
Hecho.

2022-09-19 10:20 UTC, antoniogamiz commented on doc/secciones/03_estado_del_arte.tex
> +hacer de forma que las películas que sean similares entre sí, tengan representaciones similares (cercanas).
Hecho.

2022-09-19 10:20 UTC, antoniogamiz commented on doc/secciones/03_estado_del_arte.tex
> +\emph{fruta}, o la famosa operación \emph{rey} - \emph{hombre} + \emph{mujer} = \emph{reina}.
Hecho.

2022-09-19 10:20 UTC, antoniogamiz commented on doc/secciones/03_estado_del_arte.tex
> +En el caso de este trabajo, los tropos no tienen, a priori, distintos sentidos, por lo que se ha optado
Em, me parece relevante dejar esta parte porque es la justificación de por qué uso `word2vec` y no otro modelo.

2022-09-19 10:20 UTC, antoniogamiz commented on doc/secciones/03_estado_del_arte.tex
> +el mismo word embedding es usado para kiwi y mango.
Lo he usado para justificar la elección del modelo.

2022-09-19 10:20 UTC, antoniogamiz commented on doc/secciones/03_estado_del_arte.tex
> +por usar el modelo \emph{word2vec}.
Está hecho al principio de la sección `modelos`.

2022-09-19 10:20 UTC, antoniogamiz commented on doc/bibliografia.bib
> +  title={Overview of PicTropes, a film trope dataset},
@JJ No entiendo muy bien este comentario. ¿Qué está mal en esta referencia?

2022-09-19 10:20 UTC, antoniogamiz commented on doc/secciones/01_introduccion.tex
> +En el análisis de datos de texto se suele encontrar el problema de la alta dimensionalidad de los datos. Por eso surgió el
@JJ la definición en el entorno matemático `definition` está un poco más abajo, esto es una pequeña introducción al concepto y como surgió, para no poner ahí de repente la definición.

2022-09-19 10:20 UTC, antoniogamiz commented on doc/secciones/01_introduccion.tex
> +En el análisis de datos de texto se suele encontrar el problema de la alta dimensionalidad de los datos. Por eso surgió el
No veo nada que necesite ser demostrado en este apartado.

2022-09-19 10:20 UTC, antoniogamiz commented on doc/secciones/01_introduccion.tex
> +\begin{definition}[Embedding]
La he intentado buscar pero no veo ninguna generalmente usada. La traducción sería _incrustación_ y no me gusta mucho como suena la verdad.

2022-09-19 10:20 UTC, antoniogamiz commented on doc/secciones/01_introduccion.tex
> +    Dado un conjunto de datos $D$, de tamaño $m\in\mathbb{N}$, un término $w\in D$, el embedding de $w$ es
Mm, vale puedo añadir lo de la correlación entre las columnas, pero según lo veo yo el _embedding_ no es el responsable de convertir ese elemento en un espacio de muchas dimensiones en otro con menos y fijas. El _embedding_ es solo la representación. No sé si comentar lo de _cómo las palabras que aparecen juntas_, porque eso es una forma de generar los embeddings (como hace word2vec y algoritmos similares) pero no todos los embeddings tienen por qué ser generados de esa forma, creo.

2022-09-19 10:20 UTC, antoniogamiz commented on doc/secciones/01_introduccion.tex
> +La motivación para usar \textit{embeddings} con palabras proviene de la idea de John Rupert
Vale, hablaré de la correlación entre dimensiones (ver arriba). Por _ejemplos propios_ te refieres a ejemplos hechos por mí (el del coche/camión es propio en ese caso) o a ejemplos propios del tema del trabajo, usando tropos (si es este caso, no se me ocurría ninguno que ilustrara bien el concepto).

2022-09-19 10:25 UTC, JJ commented on doc/bibliografia.bib
> +  title={Overview of PicTropes, a film trope dataset},
Mira a ver cómo sale en la sección de referencias. Por defecto, se ponen en minúsculas todas las palabras que no son principio de frase, y por tanto si no "proteges" así `PicTropes`: `{PicTropes}` aparecerá como `pictropes`

2022-09-19 10:26 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +En el análisis de datos de texto se suele encontrar el problema de la alta dimensionalidad de los datos. Por eso surgió el
Toda definición lleva consigo una hipótesis; se me ocurre aquí que sea que la semántica emerge de esta transformación, o bien que hay un mapping de un conjunto a otro que conserva una serie de características (como que codifica el contexto). Pero no soy matemático, sólo te digo que en un TFG hacen falta demostraciones.

2022-09-19 10:27 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +\begin{definition}[Embedding]
Pues cursivas

2022-09-19 10:28 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +    Dado un conjunto de datos $D$, de tamaño $m\in\mathbb{N}$, un término $w\in D$, el embedding de $w$ es
Usa la definición más aceptada y cita. Y define término, en todo caso.

2022-09-19 10:28 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +La motivación para usar \textit{embeddings} con palabras proviene de la idea de John Rupert
No, ejemplos del proyecto, usando si puedes tropos.

2022-09-19 10:29 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +En el análisis de datos de texto se suele encontrar el problema de la alta dimensionalidad de los datos. Por eso surgió el
También tendrías que intentar incluir en la definición el hecho de que para definir estos embeddings se necesita tener un contexto en el cual se suela encontrar cada término. No sé si será esencial al concepto de embedding o simplemente la forma de hacerlo, pero me da la impresión de que si.

2022-09-19 10:31 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +La motivación para usar \textit{embeddings} con palabras proviene de la idea de John Rupert
El tema es que en el proyecto se van a tomar una serie de decisiones relativas al contexto. Mientras que en PLN el concepto de "frases" está claro y el de "ventana" sobre esas frases también (aunque los números que se suelen manejar habrá que incluir demostraciones de por qué son así, los célebres 11), esos mismos conceptos tendrán que ser resultado de decisiones en los tropos, y tendrás que ponerlo así.

2022-09-19 10:34 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +En el análisis de datos de texto se suele encontrar el problema de la alta dimensionalidad de los datos. Por eso surgió el
> @JJ la definición en el entorno matemático `definition` está un poco más abajo, esto es una pequeña introducción al concepto y como surgió, para no poner ahí de repente la definición.

OK, ya lo vi al seguir leyendo. Pero cuando digas cosas como "el problema de" o lo explicas, o pones una cita, o las dos cosas. 
El problema de la dimensionalidad no lo es tal si te pillas un diccionario limitado y usas TFIDF. Trabajar con 1000 dimensiones (vocabulario habitual) o menos no es un problema para deep learning. Lo esencial de word2vec no es la reducción de dimensionalidad, sino la codificación semántica. Igual en trope2vec

2022-09-19 10:37 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +el mismo word embedding es usado para kiwi y mango.
Tú no vas a trabajar con kiwis y mangos, sino con "La pistola de Chejov" (que es un tropo) y "scrollingtitles" (otro tropo).

2022-09-20 14:42 UTC, antoniogamiz commented on doc/secciones/01_introduccion.tex
> +En el análisis de datos de texto se suele encontrar el problema de la alta dimensionalidad de los datos. Por eso surgió el
Vale, estoy de acuerdo con lo de la dimensionalidad. Con respecto a que el contexto sea necesario para la definición no. Según lo he entendido yo el `embedding` es el resultado final, una estructura (en este caso un vector numérico) que tiene codificado el valor semántico del término. En cambio, usar el contexto, es _una_ forma de generar embeddings, pero no la única. Al no ser algo intrínsico y característico de la definición, creo que no debería ser incluido en ella.

Con respecto a lo de las hipótesis y las demostraciones: va a haber demostraciones, pero cuando hagan falta (en el siguiente capítulo hay). En este caso no veo necesario (ni creo que de hecho se pueda) demostrar una definición. Lo más cercano a una demostración, es el desarrollo matemática de por qué se ha escogido la similitud coseno en lugar de otra métrica.

2022-09-20 15:04 UTC, antoniogamiz commented on doc/secciones/01_introduccion.tex
> +Análisis Semántico Latente (o más conocido por LSA, \textit{Latent Semantic Analysis}), que es una técnica popular
Done.

2022-09-20 15:09 UTC, antoniogamiz commented on doc/secciones/01_introduccion.tex
> +\begin{definition}[Embedding]
Done.

2022-09-20 15:10 UTC, antoniogamiz commented on doc/secciones/01_introduccion.tex
> +    Dado un conjunto de datos $D$, de tamaño $m\in\mathbb{N}$, un término $w\in D$, el embedding de $w$ es
He borrado el uso de _término_ y la definición está citada justo arriba de donde la he puesto.

2022-09-20 15:13 UTC, antoniogamiz commented on doc/secciones/01_introduccion.tex
> +La motivación para usar \textit{embeddings} con palabras proviene de la idea de John Rupert
¿Qué son los célebres 11? He puesto el contexto aquí porque es ese el que fue el que motivó el concepto de embeddings, no el que voy a usar en el trabajo. Cuando llegue a la sección de adaptar el contexto a mi caso particular, entonces desarrollo mi contexto particular.

2022-09-20 15:15 UTC, antoniogamiz commented on doc/secciones/01_introduccion.tex
> +La motivación para usar \textit{embeddings} con palabras proviene de la idea de John Rupert
Ejemplos con tropos no he sido capaz de generar uno que sea tan explicativo como el que hay ahora, así que creo que voy a dejar ese. Y con respecto a la correlación entre las componentes, me acabo de dar cuenta de que ya he hablado de eso (ver explicación de por qué se usa similitud coseno).

2022-09-20 15:15 UTC, JJ commented
Creo que el tamaño de la ventana que se usa para calcular los embeddings
son 11 palabras a cada lado de la que se analiza.

2022-09-20 15:16 UTC, antoniogamiz commented on doc/bibliografia.bib
> +  title={Overview of PicTropes, a film trope dataset},
Oh, no tenía ni idea, gracias.

2022-09-29 10:38 UTC, antoniogamiz commented
No veo ningún comentario adicional así que no sé si eso significa si puedo mergear y posteriormente cuando esté el TFG un poco más avanzado hacer otra revisión?

2022-09-29 15:44 UTC, JJ requested changes
*Realmente* necesitas expresar con más precisión los conocimientos matemáticos, o la parte del tribunal matemática no te lo va a dejar pasar.
Aparte, creo que falta el artículo principal del tema, que es el de los platos de cocina.

2022-09-29 15:44 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +La motivación para usar \textit{embeddings} con palabras proviene de la idea de John Rupert
Pues deberías intentarlo. Ya lo hablamos varias veces. Puede ser sustituir un arma por otra en caso de cambio de género, transporte por otro, cosas así. Pelis de vaqueros + ciencia ficción = Space opera, por ejemplo. (No son tropos exactos, pero deberías buscarlos)

2022-09-29 15:44 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +    \item El coche y otros vehículos...
También sería conveniente que fueras introduciendo progresivamente diferentes tropos de los de TVTropes, para que el tribunal se familiarice con ellos.

2022-09-29 15:44 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +ya que no cumple la desigualdad de Schwarz):
Una buena oportunidad de hacer una demostración de por qué es importante la desigualdad de Schwarz. También tendrás que citar algo, el tribunal no tiene por qué saber qué es esto.

2022-09-29 15:44 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +ningún valor semántico, sino que es la dirección del vector la que lo aporta. Sea un embedding de dimensión $d\in\mathbb{N}$, es decir,
¿Demostración? ¿Cita?

2022-09-29 15:44 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +Sin embargo, si se hubiera usado la distancia euclídea usual, la distancia entra $a$ y $b$ sería de aproximadamente $7.48$. Sería fácil encontrar otro vector $c$ igual de cercano (distancia euclídea)
Definitivamente tienes que hacer una demostración de por qué la semántica se codifica en la dirección. ¿Los vectores del embedding están normalizados? ¿Cómo lo garantizas?

2022-09-29 15:44 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +La primera noción de \textit{embedding} proviene del concepto matemático de una instancia de alguna
No creo que tenga nada que ver.

2022-09-29 15:44 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +En el caso de este trabajo, los tropos no tienen, a priori, distintos sentidos, por lo que se ha optado
No vas a usar word2vec, vas a usar any2vec

2022-09-29 15:44 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +el estudio en generar embeddings para tropos de películas.
Deberías mencionar el de los platos de cocina, que es el más importante en este sentido.

2022-09-29 18:35 UTC, antoniogamiz commented on doc/secciones/01_introduccion.tex
> +ya que no cumple la desigualdad de Schwarz):
Done.

2022-09-29 18:35 UTC, antoniogamiz commented on doc/secciones/01_introduccion.tex
> +ningún valor semántico, sino que es la dirección del vector la que lo aporta. Sea un embedding de dimensión $d\in\mathbb{N}$, es decir,
Citado.

2022-09-29 18:37 UTC, antoniogamiz commented on doc/secciones/01_introduccion.tex
> +Sin embargo, si se hubiera usado la distancia euclídea usual, la distancia entra $a$ y $b$ sería de aproximadamente $7.48$. Sería fácil encontrar otro vector $c$ igual de cercano (distancia euclídea)
Esto lo hemos discutido, está incluido en el siguiente capítulo (es el modelo quien se encarga de esto). Los vectores no están normalizados ya que, como se expresa en esos párrafos, el tamaño de los vectores no afecta a la semántica.

2022-09-29 18:37 UTC, antoniogamiz commented on doc/secciones/03_estado_del_arte.tex
> +La primera noción de \textit{embedding} proviene del concepto matemático de una instancia de alguna
Eliminado.

2022-09-29 18:37 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +\begin{definition}
¿En una definición no hay algún parámetro que diga qué defines?

2022-09-29 18:37 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +\end{definition}
Añade un label para poder referirte a ella.

2022-09-29 18:37 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +        \item Desigualdad triangular o de Schwarz: sean $x,y,z\in A$, entonces $d(x,y) \leq d(x,z) + d(z,y)$.
Schwarz o Schwartz?

2022-09-29 18:37 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +Aunque es importante notar que esta función no es de medida, ya que no cumple dos de las propiedades:
Si *es importante notar* es que tienes que poner un f*cking teorema. O un lema si es chiquitito. De verdad, que ya no sé cómo decírtelo.

2022-09-29 18:39 UTC, antoniogamiz commented on doc/secciones/01_introduccion.tex
> +        \item Desigualdad triangular o de Schwarz: sean $x,y,z\in A$, entonces $d(x,y) \leq d(x,z) + d(z,y)$.
Si Google no me engaña es Schwarz.

2022-09-30 07:02 UTC, antoniogamiz commented on doc/secciones/01_introduccion.tex
> +Aunque es importante notar que esta función no es de medida, ya que no cumple dos de las propiedades:
Done.

2022-09-30 07:04 UTC, antoniogamiz commented on doc/secciones/01_introduccion.tex
> +\end{definition}
Done.

2022-09-30 07:04 UTC, antoniogamiz commented on doc/secciones/01_introduccion.tex
> +\begin{definition}
Done.

2022-09-30 07:16 UTC, antoniogamiz commented on doc/secciones/01_introduccion.tex
> +La motivación para usar \textit{embeddings} con palabras proviene de la idea de John Rupert
Done, he buscado uno que es fácil de entender creo yo.

2022-09-30 07:17 UTC, antoniogamiz commented on doc/secciones/01_introduccion.tex
> +    \item El coche y otros vehículos...
Done.

2022-09-30 07:30 UTC, antoniogamiz commented on doc/secciones/03_estado_del_arte.tex
> +el estudio en generar embeddings para tropos de películas.
Ups, cierto. Se me ha pasado por completo, gracias por recordármelo.

2022-09-30 11:33 UTC, JJ approved these changes
:+1:  al fin

2022-09-30 11:33 UTC, JJ commented on doc/bibliografia.bib
> +  title      = {Breaking Sticks and Ambiguities with Adaptive Skip-gram},
Recuerda "proteger" las mayúsculas si Adaptive Skip-gram se suele escribir así.

2022-10-05 15:41 UTC, merged