Add use cases for first objective (#11)
antoniogamiz/tfg pull request #12
Opened 2022-02-16 19:06 UTC by antoniogamiz

2022-03-04 19:27 UTC, JJ commented
Enlaza el milestone desde el PR, no sólo desde el cuerpo. Trata de hacer cuerpos más descriptivos también, no sólo el milestone, que expliquen cuál es el issue al que se refieren y cuál HU. Conviene también que dejes claro el scope del PR.

2022-03-04 19:35 UTC, JJ requested changes
Problema principal: no están definidos los usuarios. A partir de ahí, tienes que intentar definir bien las HUs y empezar a desgajar de ellas issues == problemas a resolver (con código o teoremas)

2022-03-04 19:35 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +Del primer objetivo \ref{obj:1}, se pueden refinar los siguientes casos de uso:
Antes de los casos de uso, tienes que describir los usuarios potenciales. Los casos de uso siempre con casos de uso de *alguien*

2022-03-04 19:35 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +      \item \label{us:1} La herramienta debe ser altamente paralelizable. También debe de tener en
Caso de uso para un científico de datos, imagino. Recuerda que los casos de uso siempre se describen en el dominio del problema y desde el punto de vista del mismo, no de la implementación.

2022-03-04 19:35 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +            cuenta a la página que se está atacando, es decir, no se debe de sobrecargar de peticiones.
Estás hablando de un scraper, y eso también es un detalle de implementación. tvtropes está disponible en una versión antigua en sqlite; cómo se obtengan los datos y la velocidad no debería de ser un caso de uso.

2022-03-04 19:35 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +      \item \label{us:2} Dado el tiempo que se necesita para hacer scraping, es necesario tener un
Issue, no caso de uso. No está en el dominio del problema.

2022-03-04 19:35 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +      \item \label{us:3} La herramienta debe poder ser usada por la comunidad, es decir, debe ser
Podría ser parte de un caso de uso real, pero tendrías que definir realmente qué es "la comunidad" y qué requisitos tiene. ¿Un software como servicio? ¿Una herramienta de línea de órdenes?

2022-03-04 19:35 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +      \item \label{us:4} El formato de salida de la herramienta tiene que ser configurable. Poder elegir
También un detalle de implementación, y también dependerá de quién lo use.

2022-03-05 10:57 UTC, antoniogamiz commented
@JJ :DD

2022-03-14 17:06 UTC, JJ commented
Esto también tiene que estar en un milestone.

2022-03-14 17:11 UTC, JJ requested changes
Los usuarios están en general bien (pero tendría que verlo con más detalle), pero todavía los objetivos no se han afinado. En especial, falta un objetivo de la parte matemática: conseguir adaptar el algoritmo word2vec a conjuntos que no tengan un orden lógico, en especial los tropos en una película.

2022-03-14 17:11 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +      \item \label{obj:1} Crear una herramienta para que personas principalmente no técnicas, como
"Crear una herramienta" es a la vez vago (lo que está bien) y concreto (vas a crear algo que puedan usar). En general no debes decir qué vas a hacer para cubrir el objetivo, sólo el problema que quieres resolver, pero en este caso puede ser.

2022-03-14 17:11 UTC, JJ commented on doc/bibliografia.bib
> +@misc{configuration_milestone,
No sé si merece la pena que crees referencias para esto... Simplemente un enlace o una nota a pie de página, si acaso.

2022-03-14 17:11 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +      \item \label{obj:2} Contribuir con otra investigación al campo de los tropos, de forma que futuros
Eso va de suyo. Es demasiado genérico, y no es medible.

2022-03-14 17:11 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +      \item \label{obj:3} Crear una memoria donde se desarrolle detalladamente el trabajo realizado.
También va de suyo. No es un objetivo.

2022-03-14 17:11 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +      \item \label{obj:4} Seguir un desarrollo ágil \cite{desarrolloagil}.
No es objetivo, sino metodología.

2022-03-14 19:34 UTC, JJ requested changes
Una vuelta más y lo tienes.

2022-03-14 19:34 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +      \item \label{obj:2} Comprender la implementación del algoritmo word2vec.
Comprender es lo que tú vas a hacer para alcanzar el objetivo. Pero ¿para qué quieres comprender la implementación de word2vec? Ese es el beneficio que vas a dar al usuario.

2022-03-14 19:34 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +      \item \label{obj:3} Adaptar la implementación del algoritmo word2vec a conjuntos que no tengan un orden lógico.
Esto es una tarea, no un objetivo. El objetivo será por un lado teórico, es decir, crear la base teórica para que el algoritmo funcione y probar los teoremas correspondientes (o lo que sea) para que se puedan usar conjuntos (nos interesan tropos, pero podrían ser otros) de forma "semántica" de la misma forma que word2vec captura la "semántica" de las palabras que representa.

2022-03-14 19:34 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +      \item \label{obj:4} Crear una memoria donde se desarrolle detalladamente el trabajo realizado.
Una vez más, es una tarea y un entregable, y algo que tienes que hacer sí o si, no un objetivo. Acuérdate del documento que compartí sobre qué es un objetivo. Tiene que ser medible, alcanzable y representar un beneficio para la posible clientela.
En este caso de lo que se trata es de que la memoria sea comprensible tanto para el jurado matemático como el informático, y tanto para el tutor matemático como el informático.

2022-03-14 19:34 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +      \item Estudiante: como estudiente de la carrera, necesito presentar una memoria donde explique el trabajo realizado.
No sé yo si esto será realmente una persona. Yo creo que el cliente de esto es realmente el tribunal. También tendrías que distinguir al tribunal del tutor, quizá.

2022-03-14 19:34 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +Como tutor del trabajo necesito disponer de una forma fácil de leer el resultado final en cada
El tribunal lee el resultado final; los tutores lo van leyendo mientras se hace.

2022-03-14 19:34 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +\subsubsection*{Datos de tropos}\label{uc:trope_data}: como desarrollador necesito obtener información acerca de los
Yo diría que el caso de uso es relacionar los tropos con el rating. Estos serían subtareas del mismo. Recuerda que siempre las HUs y los casos de uso deben estar en el dominio del problema y expresar un beneficio para el usuario.

2022-03-14 19:34 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +\subsubsection*{Explicación del modelo Word2Vec}\label{uc:math}: como tutor/científico de datos/estudiante
Quien necesita entenderlo es el tribunal, tanto los informáticos como los matemáticos.

2022-03-14 19:34 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +\subsubsection*{Extensión del modelo Word2Vec}\label{uc:math}: como tutor/científico de datos/estudiante
Este sería realmente el beneficio. Lo anterior sería lo necesario para alcanzar este beneficio.

2022-04-19 15:29 UTC, antoniogamiz commented on doc/secciones/04_planificacion.tex
> +\subsubsection*{Datos de tropos}\label{uc:trope_data}: como desarrollador necesito obtener información acerca de los
Yo creo que en este caso el usuario, que es el tribunal, obtiene el beneficio de ver otra parte del trabajo desarrollado. Con su implemetanción, explicación, etc. Así que por ahora creo que voy a dejarlos separados.

2022-04-19 15:30 UTC, antoniogamiz commented on doc/secciones/04_planificacion.tex
> +\subsubsection*{Extensión del modelo Word2Vec}\label{uc:math}: como tutor/científico de datos/estudiante
Por lo mismo que lo anterior y por dejar las historias de usuarios más pequeñas para que me sea más fácil gestionarlas, voy a dejar este también separado.

2022-04-19 17:53 UTC, JJ commented
Resuelve los conflictos, porfa, para que lo revise de nuevo.

2022-04-20 16:57 UTC, JJ requested changes
Yo diría que falta todavía una vuelta. La mayoría son mini-problemas, pero la herramienta para los guionistas tienes que especificarla un poco más, sobre todo en función de qué es lo que van a tener.

2022-04-20 16:57 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +Como desarrollador necesito obtener información acerca de los
Usa siempre los stakeholders que hayas definido previamente. Este sería el científico de datos, ¿no?
En todas estas cosas, y sobre todo con vistas al tribunal, un grafiquito puede ayudar.

2022-04-20 16:57 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +\subsubsection*{Datos de rating}\label{uc:rating_data}
palabras extranjeras siempre en cursiva. Te puedo pasar la guía de estilo de El País, o pídele a Ceci que te la lleve.

2022-04-20 16:57 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +\subsubsection*{Extensión del modelo Word2Vec}\label{uc:math_extension}
Más bien necesitas extender el modelo word2vec de forma que se adapte al problema que se está tratando.

2022-04-20 16:57 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +fácil de usar que no requiera conocimientos técnicos para ser usada.
Para hacer ¿qué? ¿Qué tengo y qué quiero obtener?

2022-04-21 19:21 UTC, antoniogamiz commented
He agrupado las minitareas en historias con un poco más de sentido. La parte de incluir el rating la he dejado un una historia aparte para añadir cuando se tenga un primer MVP.

2022-04-22 06:41 UTC, JJ requested changes
Me temo que necesita una vuelta más por los temas resueltos que no se han justificado, y la última historia de usuario.

2022-04-22 06:41 UTC, JJ commented on doc/proyecto.tex
> +% \input{portada/portada}
?

2022-04-22 06:41 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +fácil de usar que no requiera conocimientos técnicos para ser usada.
¿por qué las has resuelto? No las resuelvas sin cambiar el texto o justificarlo...

2022-04-22 06:41 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +Como desarrollador necesito obtener información acerca del \textit{rating}
Los desarrolladores nunca tienen historias de usuario, tienen tickets asociados a las historias de usuario. ¿Cuál es el beneficio para el usuario aquí? ¿Qué se consigue "considerando"?

2022-04-22 06:41 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +Como tribunal/tutor/científico de datos
Los rating no extienden word2vec, simplemente asocian los resultados de word2vec a un rating, para examinar su "coherencia" a través de su "éxito"

2022-04-23 06:32 UTC, antoniogamiz commented on doc/secciones/04_planificacion.tex
> +Como desarrollador necesito obtener información acerca del \textit{rating}
Ciertamente, lo quito de ahi y lo creo como ticket.

2022-04-23 06:35 UTC, antoniogamiz commented on doc/secciones/04_planificacion.tex
> +Como tribunal/tutor/científico de datos
Cierto, cambiado.

2022-04-23 06:36 UTC, antoniogamiz commented on doc/proyecto.tex
> +% \input{portada/portada}
Ups, fallo mío al commitear.

2022-04-23 06:52 UTC, antoniogamiz commented on doc/secciones/04_planificacion.tex
> +fácil de usar que no requiera conocimientos técnicos para ser usada.
La marqué como resuelta porque añadí los criterios de aceptación en lugar de moficar el texto.

2022-04-25 12:25 UTC, JJ approved these changes
:+1:

2022-07-07 05:38 UTC, merged