Crea release (manual) cuando se alcanza un milestone
antoniogamiz/tfg pull request #28
Opened 2022-03-07 17:39 UTC by antoniogamiz

## Scope

Con este PR se pretende crear un workflow para poder publicar una versión del PDF completo una vez se haya alcanzado algún hito. 

## Referencias

- Historia de usuario: #33 
- Closes: #1

2022-03-09 13:25 UTC, JJ commented
Todo PR tiene que solucionar un issue o issues, que a su vez deben estar relacionados con una historia de usuario.

2022-03-14 15:54 UTC, antoniogamiz commented
Este PR soluciona un issue del primer milestone, que soluciona el primer caso de uso (#12 ).

2022-03-14 17:51 UTC, JJ requested changes
El workflow está bien, pero 
1. Tiene que haber un issue que describa exactamente lo que quieres hacer y cuando. Por ejemplo, igual tienes que comprobar si el LaTeX compila *siempre*. Y el release se puede hacer cuando tagees, o mergees a main. Es algo que tienes que decidir, y para eso tienes que describir el problema en un issue.
2. Tendrías que tener workflows adicionales para comprobación ortográfica, por ejemplo.

2022-03-14 17:51 UTC, JJ commented on .github/workflows/release.yml
> +  workflow_dispatch:
¿Por qué manual y no cuando se haga un tag o algo?

2022-03-14 18:10 UTC, antoniogamiz commented on .github/workflows/release.yml
> +  workflow_dispatch:
Porque este workflow manual crea el tag y la release. Prefiero decidir cuando lanzar un PMV con un click.

2022-03-14 18:41 UTC, JJ commented on .github/workflows/release.yml
> +  workflow_dispatch:
OK, ya veo. En ese caso tendrías que ver la forma de lanzar el workflow para que el tag siga "Semantic versioning". Tagearlo con un sha no es muy amistoso para el usuario.

2022-03-14 18:43 UTC, JJ requested changes
OK con lo que me dices, si pones un tag razonable (una vez más, una buena razón para que los PRs *siempre* sigan un issue.

2022-03-14 18:43 UTC, JJ commented on .github/workflows/release.yml
> +          tag_name: ${{ github.sha }}
En vez de hacerlos automáticamente, usa argumentos para el workflow para que estos tengan un nombre razonable (y se incluya de alguna forma la descripción dle mismo)

2022-03-14 18:55 UTC, antoniogamiz commented on .github/workflows/release.yml
> +  workflow_dispatch:
Me parece razonable. Lo haré manual (con un input argument)  y luego si es necesario haré una mejora incremental.

2022-03-14 18:57 UTC, antoniogamiz commented on .github/workflows/release.yml
> +          tag_name: ${{ github.sha }}
De acuerdo. Para la descripción del mismo creo que voy a poner un resumen auto generado de las issues que se han cerrado. He empezado a usar conventional commits así que debería quedar bastante claro qué incluye cada MVP.

2022-03-14 19:19 UTC, merged