Planificación del proyecto
antoniogamiz/tfg pull request #46
Opened 2022-09-29 11:27 UTC by antoniogamiz

## Scope

Detallar la planificación del proyecto.

### Referencias

- Historia de usuario: closes #34
- Issue: #34

2022-09-29 11:28 UTC, antoniogamiz commented
Además de actualizar las milestones, he creado este PR apuntando a la rama del estado del arte para evitar conflictos.

2022-09-29 15:34 UTC, JJ requested changes
No creo que debas recortar esto, al menos la parte que has hecho.

2022-09-29 15:34 UTC, JJ commented on doc/secciones/04_planificacion.tex
> -      \item Dado un tropo, se debe poder obtener el más similar semánticamente.
Esto es el objetivo principal. No puedes eliminarlo.

2022-09-29 15:34 UTC, JJ commented on doc/secciones/04_planificacion.tex
> -\subsection{[HU3] Considerar datos sobre \textit{rating}}\label{uc:word2vec_rating}
No habría gran problema con esto, aunque evidentemente lo principal es poder generar nuevas historias. Puedes eliminarlo, sin embargo, o simplemetne decir que en el desarrollo no se ha llegado a eso.

2022-10-03 11:25 UTC, JJ requested changes
Una pequeña vuelta, sobre todo especificando un poco más.

2022-10-03 11:25 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +\subsubsection{[HU2 ]Primera extensión del modelo Word2Vec}\label{uc:word2vec_primera_extension}
Normalmente la HU del tribunal no se pone en la memoria. Si quieres dejarlo como documentación para un científico de datos, puede valer.

2022-10-03 11:25 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +      \item \href{https://github.com/antoniogamiz/tfg/milestone/1}{Milestone 0 - Configuración inicial}
Explica en cada uno de ellos cuál es el entregable o producto mínimamente viable.

2022-10-12 09:36 UTC, antoniogamiz commented
Añadí cambios aquí, no se si los viste.

2022-10-12 11:50 UTC, JJ commented
> Añadí cambios aquí, no se si los viste.

Avísame explícitamente cuando quieras que revise, por favor. No sé si es WIP que espera algún commit más.

2022-10-12 11:52 UTC, JJ approved these changes
Creo que a estas alturas lo mejor es aprobar, pero faltaría un milestone que actualizaría los datos, porque los que hay ahora mismo son de hace por lo menos tres años; y al actualizar puede que sea necesario también actualizar tropescraper. Lo puedes poner como un PMV al final por si hubiera tiempo.

2022-10-12 11:52 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +      \item \href{https://github.com/antoniogamiz/tfg/milestone/4}{Milestone 1 - Teoría modelo \textit{Word2Vec}}: el objetivo es tener la fundación matemática del modelo usado desarrollada.
En línea con los comentarios del otro PR, creo que deberías poner any2vec o similar. O si haces sólo word2vec, explicar cómo se modificaría en este caso.

2022-10-13 05:42 UTC, merged